version: "3"
services:
  app:
    build: ./
    container_name: RestApi-app
    ports:
      - 8082:8082
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/DelesBlog
        SPRING_DATASOURCE_PASSWORD: Postgres1
        SPRING_DATASOURCE_USERNAME: postgres
    depends_on:
      - db
    networks:
      - rest-api

  db:
    image: postgres:latest
    container_name: postgresDB
    ports:
      - 5432:5433
      - 2
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Postgres1
      POSTGRES_DB: securitytest
    networks:
      - rest-api

networks:
  rest-api:
    driver: bridge

